# Generated by Django 4.0.5 on 2022-06-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_books',
            name='book_file',
            field=models.FileField(null=True, upload_to='files/', verbose_name=''),
        ),
    ]
