# Generated by Django 4.0.5 on 2022-06-21 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_my_books_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_books',
            name='book_cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name=''),
            preserve_default=False,
        ),
    ]
