# Generated by Django 4.0.5 on 2022-06-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_my_books_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_books',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='base/files/covers'),
        ),
        migrations.AlterField(
            model_name='my_books',
            name='book_file',
            field=models.FileField(null=True, upload_to='base/files/pdfs', verbose_name=''),
        ),
    ]
