# Generated by Django 4.0.5 on 2022-06-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_my_book_rename_students_student_delete_my_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_book',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='my_book',
            name='book_file',
        ),
    ]
