# Generated by Django 4.0.5 on 2022-06-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_name_my_book_title_remove_my_book_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_book',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
