# Generated by Django 4.0.5 on 2022-07-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_my_book_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requested_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.my_book')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowed_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(verbose_name=models.DateTimeField(auto_now_add=True))),
                ('date_returned', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.my_book')),
            ],
        ),
    ]
