# Generated by Django 4.0.5 on 2022-07-08 12:29

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_requested_book_borrowed_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='base/files/covers/'),
        ),
    ]
