# Generated by Django 4.0.5 on 2022-07-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_my_book_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
